# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRepaymentType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('repayment_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_date', models.DateTimeField()),
                ('last_modified_by', models.BigIntegerField()),
                ('master_repayment_type_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_repayment_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterStatus',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, unique=True)),
                ('last_updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'master_status',
                'managed': False,
            },
        ),
    ]
