# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.BigIntegerField()),
                ('author', models.CharField(max_length=10, unique=True)),
                ('text', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'master_author',
                'managed': False,
            },
        ),
    ]
